# Nome do Workflow: Este nome aparecerá na lista de Actions.
name: 'Criar Arquivos para Nova Funcionalidade'

# Gatilho (Trigger): Permite que este fluxo seja acionado manualmente.
on:
  workflow_dispatch:
    inputs:
      # Campo para o nome da pasta da funcionalidade.
      feature_folder_name:
        description: 'Nome da pasta da nova funcionalidade (ex: TelaFeed)'
        required: true
        default: 'TelaFeed' # Valor padrão para a pasta.
      
      # Campo para escolher a branch.
      branch_name:
        description: 'Nome da branch onde os arquivos serão criados'
        required: true
        default: 'gabriel' # CORREÇÃO: Coloquei 'gabriel' como o valor padrão.

# Tarefas (Jobs) a serem executadas.
jobs:
  create_files:
    # O "servidor" temporário que vai rodar os comandos.
    runs-on: ubuntu-latest

    # Passos (Steps) da tarefa.
    steps:
      # Passo 1: Baixar o código da branch que você especificou.
      - name: 1. Baixar o código da branch especificada
        uses: actions/checkout@v4
        with:
          # Usa o valor do campo 'branch_name' para saber qual branch baixar.
          ref: ${{ github.event.inputs.branch_name }}

      # Passo 2: Criar a estrutura de pastas e os arquivos.
      - name: 2. Criar pasta e arquivos da funcionalidade
        run: |
          FOLDER_NAME=${{ github.event.inputs.feature_folder_name }}
          TARGET_PATH="telasHTML/ArquivosGerais/$FOLDER_NAME"
          mkdir -p "$TARGET_PATH"
          touch "$TARGET_PATH/feed.html"
          touch "$TARGET_PATH/feed.css"
          touch "$TARGET_PATH/feed.js"
          echo "Estrutura de arquivos para '$FOLDER_NAME' criada em '$TARGET_PATH'."

      # Passo 3: Fazer o commit e enviar as alterações de volta para a branch.
      - name: 3. Fazer commit e push dos novos arquivos
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@github.com'
          git add .
          git commit -m "CI: Cria automaticamente a estrutura de arquivos para a funcionalidade ${{ github.event.inputs.feature_folder_name }}"
          git push
